# -*- coding: utf-8 -*-
"""Example Usage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19IpJ3wr9U68V7M3WUn3XdSuwrWwVXqsS

Example script for using the KFCRegressor and KFCClassifier
"""

import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.cluster import KMeans, MiniBatchKMeans
from sklearn.datasets import make_regression, make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score
from kfc_model.combiner import MeanCombiner, VotingCombiner
from kfc_model.classifier import KFCClassifier
from kfc_model.regressor import KFCRegressor

def run_regression_example():
    """
    Demonstrates the KFCRegressor
    """
    print("--- Running KFCRegressor Example ---")

    # 1. Define components
    # K: Two different clusterings (M=2)
    clusterer1 = KMeans(n_clusters=4, n_init=10, random_state=1)
    clusterer2 = MiniBatchKMeans(n_clusters=8, n_init=10, random_state=2)

    # F: Local model
    local_model = LinearRegression()

    # C: Combiner
    combiner = MeanCombiner()

    # 2. Create the KFCRegressor
    kfc_reg = KFCRegressor(
        clusterers=[clusterer1, clusterer2],
        local_estimator=local_model,
        combiner=combiner
    )

    # 3. Load data and fit
    X, y = make_regression(
        n_samples=2000,
        n_features=10,
        n_informative=5,
        noise=20,
        random_state=42
    )
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    kfc_reg.fit(X_train, y_train)

    # 4. Make predictions
    y_pred = kfc_reg.predict(X_test)

    # 5. Evaluate
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    print(f"KFCRegressor RMSE: {rmse:.4f}")

    # Compare to a single Linear Regression
    lr = LinearRegression()
    lr.fit(X_train, y_train)
    y_pred_lr = lr.predict(X_test)
    rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
    print(f"Standard LinearRegression RMSE: {rmse_lr:.4f}")
    print("------------------------------------\n")


def run_classification_example():
    """
    Demonstrates the KFCClassifier
    """
    print("--- Running KFCClassifier Example ---")

    # 1. Define components
    # K: One clustering (M=1)
    clusterer1 = KMeans(n_clusters=3, n_init=10, random_state=1)

    # F: Local model
    local_model = LogisticRegression(solver='lbfgs')

    # C: Combiner
    combiner = VotingCombiner() # Use VotingCombiner for labels, MeanCombiner for probas

    # 2. Create the KFCClassifier
    kfc_clf = KFCClassifier(
        clusterers=[clusterer1],
        local_estimator=local_model,
        combiner=combiner
    )

    # 3. Load data and fit
    X, y = make_classification(n_samples=1000, n_features=10, n_informative=5,
                               n_redundant=0, n_classes=3, n_clusters_per_class=1, random_state=42)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    kfc_clf.fit(X_train, y_train)

    # 4. Make predictions
    y_pred = kfc_clf.predict(X_test)
    y_proba = kfc_clf.predict_proba(X_test)

    # 5. Evaluate
    acc = accuracy_score(y_test, y_pred)
    print(f"KFCClassifier Accuracy: {acc:.4f}")
    # print(f"Example Probabilities:\n{y_proba[:3]}")

    # Compare to a single Logistic Regression
    lr = LogisticRegression(solver='lbfgs')
    lr.fit(X_train, y_train)
    y_pred_lr = lr.predict(X_test)
    acc_lr = accuracy_score(y_test, y_pred_lr)
    print(f"Standard LogisticRegression Accuracy: {acc_lr:.4f}")
    print("--------------------------------------\n")

    print(f"Predict Proba: {y_proba}")

if __name__ == "__main__":
    run_regression_example()
    run_classification_example()
