# -*- coding: utf-8 -*-
"""Package Setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zX86i25QjGlSdyIIGrtbfXVWFqQuJznA
"""

from setuptools import setup, find_packages

setup(
    name='kfc_model',
    version='0.1.0',
    description='' \
    'Implementation of the KFC (K-means, Fitting, Combining) procedure for predictive modeling.',
    author='Your Name',
    author_email='your.email@example.com',
    packages=find_packages(),
    install_requires=[
        'numpy',
        'scipy',
        'scikit-learn',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
    ],
    python_requires='>=3.8',
)
