# -*- coding: utf-8 -*-
"""Package Init

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkcK6THgOPpg0c5MI43RYpvR8Tg46VUf
"""

"""
KFC-Model Package
=================

This package provides scikit-learn compatible implementations of the
KFC (K-means, Fitting, Combining) procedure for regression and classification.

Main Components:
- KFCRegressor: The main regression estimator.
- KFCClassifier: The main classification estimator.
- BaseKFC: The abstract base class for all KFC estimators.
- combiners: A module with abstract and concrete combination strategies.
"""

__version__ = "0.1.0"

from .regressor import KFCRegressor
from .classifier import KFCClassifier
from .base import BaseKFC
from .combiner import *
from .local_model import *
from .divergence import *
from .model import KFCModel

__all__ = [
    'BaseKFC',
    'KFCModel',
    'KFCRegressor',
    'KFCClassifier',
    'combiner',
]