# -*- coding: utf-8 -*-
"""KFC Regressor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HLt_7ujcAv6rCtJnp8Y66MxnwIA8eRH

KFCRegressor: Concrete implementation for regression
"""

from sklearn.base import RegressorMixin
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

from .base import BaseKFC
from .combiner import MeanCombiner

class KFCRegressor(BaseKFC, RegressorMixin):
    """
    KFC (K-means, Fitting, Combining) Regressor.

    Parameters
    ----------
    local_estimator : estimator object, default=LinearRegression()
        The base regressor to be fitted on each cluster.
        If None, LinearRegression() is used.

    clusterers : list of clusterer objects, default=[KMeans(n_clusters=5)]
        A list of M clustering algorithms.
        If None, a single KMeans(n_clusters=5) is used.

    combiner : BaseCombiner object, default=MeanCombiner()
        The strategy for aggregating the M candidate predictions.
        If None, MeanCombiner() is used.
    """

    def __init__(self, local_estimator=None, clusterers=None, combiner=None):

        # Set default components if None
        if local_estimator is None:
            local_estimator = LinearRegression()

        if clusterers is None:
            clusterers = [KMeans(n_clusters=5, n_init=10, random_state=0)]

        if combiner is None:
            combiner = MeanCombiner()

        super().__init__(
            local_estimator=local_estimator,
            clusterers=clusterers,
            combiner=combiner
        )

    def _get_estimator_type(self):
        return "regressor"
