# -*- coding: utf-8 -*-
"""Validation Utilities

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubKzqBpnpIk95Xzt2gilcjQT0O3bwEs7
"""

"""
Utility and validation functions for the KFC-Model package.

As the package grows, you can add helper functions here,
such as custom checks or functions to handle specific clusterers.
"""

import numpy as np

def check_clusterer_list(clusterers):
    """
    Validates the `clusterers` parameter.

    This is a placeholder for more advanced validation, e.g.,
    ensuring each item has a `fit` and `predict` method.
    """
    if not isinstance(clusterers, list) or len(clusterers) == 0:
        raise ValueError("`clusterers` must be a non-empty list of clustering estimators.")

    for i, clusterer in enumerate(clusterers):
        if not (hasattr(clusterer, 'fit') and hasattr(clusterer, 'predict')):
            raise TypeError(
                f"Clusterer at index {i} ({type(clusterer).__name__}) "
                "does not have the required 'fit' and 'predict' methods."
            )
    return clusterers
