# -*- coding: utf-8 -*-
"""Validation Utilities (Empty)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mukh9u5zOZBw0e7hhifpiSYmpTx1NLEg
"""

# kfc_model/utils/__init__.py
# This file can be left empty